import artworksJson from "@/lib/data/artworks.json";

export const SITE_URL = "https://www.elyio.co";
export const LOCALES = ["en", "fr", "zh-hans"] as const;
export type SeoLocale = (typeof LOCALES)[number];
export type SeoReadiness = "SEO_READY_CURATED" | "SEO_READY_FACTUAL" | "GENERATED_ENRICHED" | "THIN_INSUFFICIENT" | "PRIVATE_USER_STATE";

export const localeNames: Record<SeoLocale, string> = { en: "English", fr: "Français", "zh-hans": "简体中文" };

type LocalText = Record<SeoLocale, string>;
type MuseumContent = {
  id: string; slug: string; name: string; city: string; website: string;
  readiness: SeoReadiness; intro: LocalText; focus: LocalText; highlights: LocalText;
};

const t = (en: string, fr: string, zh: string): LocalText => ({ en, fr, "zh-hans": zh });

export const museums: MuseumContent[] = [
  { id:"louvre", slug:"musee-du-louvre", name:"Musée du Louvre", city:"Paris", website:"https://www.louvre.fr/", readiness:"SEO_READY_CURATED",
    intro:t("Plan a Louvre visit around close looking, not a race through its galleries. ELYIO supports a curated selection of works with concise stories, visual clues and clearly labelled value context.","Préparez une visite du Louvre fondée sur l’observation plutôt que sur une course dans les galeries. ELYIO accompagne une sélection d’œuvres avec des récits concis, des clés visuelles et un contexte de valeur clairement identifié.","用细看作品的方式规划卢浮宫之行，而不是匆匆打卡。ELYIO 为精选作品提供简明故事、观看线索和明确标注的价值背景。"),
    focus:t("The collection spans ancient civilizations, European painting, sculpture and decorative arts. Start with a few anchors, then leave time for the rooms between them.","Les collections couvrent les civilisations antiques, la peinture européenne, la sculpture et les arts décoratifs. Choisissez quelques repères, puis gardez du temps pour les salles qui les relient.","馆藏横跨古代文明、欧洲绘画、雕塑与装饰艺术。先选择少数重点，再为沿途展厅留出时间。"), highlights:t("Mona Lisa; Winged Victory of Samothrace; Venus de Milo","La Joconde ; Victoire de Samothrace ; Vénus de Milo","《蒙娜丽莎》；萨莫色雷斯的胜利女神；米洛的维纳斯") },
  { id:"orsay", slug:"musee-d-orsay", name:"Musée d’Orsay", city:"Paris", website:"https://www.musee-orsay.fr/", readiness:"SEO_READY_CURATED",
    intro:t("ELYIO’s Orsay guide connects the former railway station’s celebrated paintings and sculptures to details you can inspect in front of the work.","Le guide ELYIO d’Orsay relie les célèbres peintures et sculptures de l’ancienne gare aux détails que vous pouvez observer devant l’œuvre.","ELYIO 奥赛指南把这座旧火车站中的著名绘画与雕塑，连接到您可在作品前亲自观察的细节。"), focus:t("The museum is especially strong in art from 1848 to 1914, including Realism, Impressionism and Post-Impressionism. The upper-level galleries give a useful chronological route.","Le musée est particulièrement riche pour la période 1848-1914, du réalisme au postimpressionnisme. Les galeries supérieures offrent un parcours chronologique clair.","博物馆尤以 1848 至 1914 年艺术见长，涵盖现实主义、印象派与后印象派。顶层展厅提供清晰的时间线。"), highlights:t("Van Gogh’s Starry Night Over the Rhône; Manet’s Olympia; Degas’s Little Dancer","La Nuit étoilée de Van Gogh ; Olympia de Manet ; La Petite Danseuse de Degas","梵高《罗讷河上的星夜》；马奈《奥林匹亚》；德加《十四岁的小舞者》") },
  { id:"orangerie", slug:"musee-de-l-orangerie", name:"Musée de l’Orangerie", city:"Paris", website:"https://www.musee-orangerie.fr/", readiness:"SEO_READY_CURATED", intro:t("Use ELYIO to slow down in Monet’s panoramic Water Lilies rooms, then explore the compact Walter-Guillaume collection downstairs.","Avec ELYIO, prenez le temps dans les salles panoramiques des Nymphéas de Monet, puis découvrez la collection Walter-Guillaume au niveau inférieur.","借助 ELYIO 在莫奈全景《睡莲》展厅中放慢脚步，再探索楼下精炼的沃尔特-纪尧姆收藏。"), focus:t("The oval rooms were conceived around light, water and continuous viewing. Downstairs, works by Renoir, Cézanne, Modigliani, Soutine and others form a concentrated modern collection.","Les salles ovales sont conçues autour de la lumière, de l’eau et d’un regard continu. En bas, Renoir, Cézanne, Modigliani ou Soutine composent une collection moderne très dense.","椭圆展厅围绕光、水和连续观看而设计。楼下由雷诺阿、塞尚、莫迪利亚尼、苏丁等人的作品构成密集的现代艺术收藏。"), highlights:t("Monet’s Water Lilies; Renoir; Modigliani and Soutine","Les Nymphéas de Monet ; Renoir ; Modigliani et Soutine","莫奈《睡莲》；雷诺阿；莫迪利亚尼与苏丁") },
  { id:"museofile_m1104", slug:"musee-carnavalet", name:"Musée Carnavalet", city:"Paris", website:"https://www.carnavalet.paris.fr/", readiness:"SEO_READY_CURATED", intro:t("Carnavalet tells the history of Paris through interiors, paintings, signs, objects and fragments of the city itself. ELYIO helps connect individual objects to the changing streets outside.","Carnavalet raconte l’histoire de Paris par des décors, peintures, enseignes, objets et fragments de la ville. ELYIO relie chaque œuvre aux rues qui ont changé autour du musée.","卡纳瓦雷博物馆通过室内陈设、绘画、招牌、器物与城市遗存讲述巴黎史。ELYIO 帮助把单件展品与馆外不断变化的街道联系起来。"), focus:t("Follow the chronological rooms from prehistoric Paris through the Revolution and into the modern city; reconstructed period rooms reward careful looking.","Suivez les salles chronologiques, du Paris préhistorique à la Révolution puis à la ville moderne ; les décors reconstitués méritent une observation attentive.","沿时间顺序从史前巴黎、法国大革命走向现代城市；复原的历史室内空间值得仔细观看。"), highlights:t("French Revolution collections; historic Paris shop signs; reconstructed period rooms","Collections de la Révolution française ; enseignes parisiennes ; décors historiques","法国大革命收藏；巴黎历史店招；复原时代房间") },
  { id:"museofile_m5003", slug:"musee-de-cluny", name:"Musée de Cluny", city:"Paris", website:"https://www.musee-moyenage.fr/", readiness:"SEO_READY_CURATED", intro:t("Cluny places medieval art inside a site where Roman baths meet a late-medieval townhouse. ELYIO highlights materials, symbols and the slow craft behind the objects.","Cluny présente l’art médiéval dans un lieu où les thermes antiques rencontrent un hôtel de la fin du Moyen Âge. ELYIO éclaire les matières, les symboles et les savoir-faire.","克吕尼博物馆在古罗马浴场与中世纪晚期府邸交汇的建筑中呈现中世纪艺术。ELYIO 聚焦材质、象征与缓慢精细的工艺。"), focus:t("Allow time for the building as well as the collection. Tapestry, stained glass, sculpture and metalwork reveal different kinds of medieval image-making.","Accordez autant d’attention au bâtiment qu’aux collections. Tapisserie, vitrail, sculpture et orfèvrerie montrent diverses façons médiévales de créer des images.","除了藏品，也请留意建筑本身。挂毯、彩色玻璃、雕塑与金属工艺展现中世纪多样的图像创造方式。"), highlights:t("The Lady and the Unicorn tapestries; Gallo-Roman baths; medieval sculpture","Les tapisseries de La Dame à la licorne ; thermes gallo-romains ; sculpture médiévale","《贵妇与独角兽》挂毯；高卢-罗马浴场；中世纪雕塑") },
  { id:"museofile_m5025", slug:"musee-de-l-armee", name:"Musée de l’Armée", city:"Paris", website:"https://www.musee-armee.fr/accueil.html", readiness:"SEO_READY_CURATED", intro:t("At Les Invalides, ELYIO reads armour, uniforms, paintings and memorial spaces as designed objects as well as historical evidence.","Aux Invalides, ELYIO aborde armures, uniformes, peintures et espaces mémoriels comme des objets conçus autant que comme des témoignages historiques.","在荣军院，ELYIO 将盔甲、军服、绘画与纪念空间同时视为设计物和历史证据。"), focus:t("The displays cover warfare from medieval armour to the world wars. Keep historical context separate from admiration of craftsmanship, especially in rooms devoted to modern conflict.","Le parcours va des armures médiévales aux guerres mondiales. Il faut distinguer le contexte historique de l’admiration du savoir-faire, notamment pour les conflits modernes.","展陈从中世纪盔甲延伸至世界大战。在现代战争展厅，尤其应区分历史语境与对工艺的欣赏。"), highlights:t("Historic armour; Napoleon’s tomb; First and Second World War galleries","Armures historiques ; tombeau de Napoléon ; salles des deux guerres mondiales","历史盔甲；拿破仑墓；两次世界大战展厅") },
  { id:"museofile_m5055", slug:"musee-du-quai-branly-jacques-chirac", name:"Musée du quai Branly – Jacques Chirac", city:"Paris", website:"https://www.quaibranly.fr/fr/", readiness:"SEO_READY_CURATED", intro:t("ELYIO supports close looking at works from Africa, Asia, Oceania and the Americas while keeping provenance, use and colonial collecting histories in view.","ELYIO accompagne l’observation des œuvres d’Afrique, d’Asie, d’Océanie et des Amériques, sans perdre de vue provenance, usage et histoire coloniale des collections.","ELYIO 引导细看来自非洲、亚洲、大洋洲和美洲的作品，同时关注其来源、用途与殖民收藏史。"), focus:t("Objects were made for particular communities and purposes before entering a Paris museum. Read labels for origin and provenance, and avoid treating broad geographic groupings as a single culture.","Ces objets avaient des usages et des communautés propres avant leur entrée au musée. Lisez les indications d’origine et de provenance sans réduire de vastes régions à une culture unique.","这些物件进入巴黎博物馆前属于特定社群并有具体用途。请阅读来源信息，不要把广阔地域视为单一文化。"), highlights:t("African sculpture; Oceanic art; textiles and objects from the Americas","Sculptures africaines ; arts d’Océanie ; textiles et objets des Amériques","非洲雕塑；大洋洲艺术；美洲纺织品与器物") },
  { id:"museofile_m5005", slug:"musee-guimet", name:"Musée Guimet", city:"Paris", website:"https://www.museeguimet.fr", readiness:"SEO_READY_CURATED", intro:t("Guimet’s Asian art collections reward attention to material, ritual function and the movement of forms across regions. ELYIO provides visual entry points without flattening distinct cultures.","Les collections asiatiques de Guimet invitent à observer matières, usages rituels et circulation des formes. ELYIO propose des clés visuelles sans confondre des cultures distinctes.","吉美博物馆的亚洲艺术收藏值得从材质、仪式功能与形式跨地域传播来观察。ELYIO 提供视觉入口，同时尊重不同文化的差异。"), focus:t("The galleries range from South and Southeast Asia to China, Korea, Japan and the Himalayan world. Choose one region at a time rather than trying to cover every floor.","Les galeries vont de l’Asie du Sud et du Sud-Est à la Chine, la Corée, le Japon et l’Himalaya. Mieux vaut choisir une région que vouloir parcourir tous les étages.","展厅覆盖南亚、东南亚、中国、韩国、日本与喜马拉雅地区。建议一次专注一个区域，而非赶遍所有楼层。"), highlights:t("Khmer sculpture; Buddhist art; Chinese ceramics and Japanese works","Sculpture khmère ; arts bouddhiques ; céramiques chinoises et œuvres japonaises","高棉雕塑；佛教艺术；中国陶瓷与日本艺术") },
  { id:"museofile_m5043", slug:"musee-picasso-paris", name:"Musée Picasso Paris", city:"Paris", website:"https://www.museepicassoparis.fr/", readiness:"SEO_READY_CURATED", intro:t("Picasso’s own collection and a broad group of his works fill the Hôtel Salé. ELYIO helps follow changes in medium and approach rather than reducing a long career to one style.","La collection personnelle de Picasso et un vaste ensemble de ses œuvres occupent l’Hôtel Salé. ELYIO suit les changements de technique et de démarche sans réduire une longue carrière à un seul style.","毕加索个人收藏及其大量作品陈列于萨莱府邸。ELYIO 帮助追踪媒介与方法的变化，避免把漫长创作生涯简化为单一风格。"), focus:t("Look across painting, drawing, sculpture, printmaking and ceramics. Dates matter: compare works made decades apart before assuming that distortion always means the same thing.","Regardez peinture, dessin, sculpture, gravure et céramique. Les dates comptent : comparez des œuvres éloignées dans le temps avant d’attribuer toujours le même sens aux déformations.","请跨绘画、素描、雕塑、版画与陶瓷观看。年代很重要：先比较相隔数十年的作品，不要假定变形总有同一含义。"), highlights:t("Picasso’s paintings and sculpture; his personal collection; the Hôtel Salé","Peintures et sculptures de Picasso ; sa collection personnelle ; l’Hôtel Salé","毕加索绘画与雕塑；其个人收藏；萨莱府邸") },
  { id:"museofile_m5044", slug:"musee-rodin", name:"Musée Rodin", city:"Paris", website:"https://www.musee-rodin.fr/", readiness:"SEO_READY_CURATED", intro:t("ELYIO’s Rodin guide links bronze and marble surfaces to the sculptor’s repeated use of fragments, casts and changing compositions across the Hôtel Biron and garden.","Le guide ELYIO relie les surfaces du bronze et du marbre aux fragments, moulages et compositions que Rodin remaniait entre l’Hôtel Biron et le jardin.","ELYIO 罗丹指南把青铜与大理石表面，连接到雕塑家在比隆府邸和花园中反复使用的残片、铸模与变化构图。"), focus:t("Walk around sculpture whenever the display allows: silhouette, negative space and surface change with viewpoint. The garden gives monumental bronzes room to be seen at a distance.","Tournez autour des sculptures lorsque c’est possible : silhouette, vide et surface changent selon le point de vue. Le jardin permet de voir les grands bronzes à distance.","条件允许时请绕雕塑观看：轮廓、负空间与表面会随视角变化。花园让大型青铜作品能从远处被看见。"), highlights:t("The Thinker; The Kiss; The Gates of Hell","Le Penseur ; Le Baiser ; La Porte de l’Enfer","《思想者》；《吻》；《地狱之门》") },
  { id:"museofile_m1111", slug:"petit-palais", name:"Petit Palais", city:"Paris", website:"https://www.petitpalais.paris.fr/", readiness:"SEO_READY_CURATED", intro:t("The Petit Palais combines fine art, decorative art and an architecture built for the 1900 Exposition. ELYIO helps connect individual works to the building’s ambitious public setting.","Le Petit Palais réunit beaux-arts, arts décoratifs et architecture de l’Exposition de 1900. ELYIO relie les œuvres au cadre public ambitieux du bâtiment.","小皇宫汇集纯艺术、装饰艺术与为 1900 年世博会建造的建筑。ELYIO 帮助把单件作品与宏大的公共空间联系起来。"), focus:t("The permanent collection moves from antiquity to the early twentieth century. Notice the painted ceilings, mosaic floors and garden courtyard as part of the visit.","La collection permanente va de l’Antiquité au début du XXe siècle. Plafonds peints, sols en mosaïque et jardin intérieur font partie de la visite.","常设收藏从古代延伸至 20 世纪初。彩绘天花板、马赛克地面与庭院花园也都是参观的一部分。"), highlights:t("Nineteenth-century painting; decorative arts; the Beaux-Arts building and courtyard","Peinture du XIXe siècle ; arts décoratifs ; architecture et jardin","19 世纪绘画；装饰艺术；美术学院派建筑与庭院") },
  { id:"versailles", slug:"chateau-de-versailles", name:"Château de Versailles", city:"Versailles", website:"https://www.chateauversailles.fr/", readiness:"SEO_READY_CURATED", intro:t("Versailles is palace, political stage, museum and designed landscape. ELYIO helps read paintings, rooms and objects in relation to ceremony, power and the people who made them.","Versailles est à la fois palais, scène politique, musée et paysage composé. ELYIO relie peintures, salles et objets aux cérémonies, au pouvoir et à ceux qui les ont fabriqués.","凡尔赛既是宫殿、政治舞台、博物馆，也是精心设计的景观。ELYIO 帮助从礼仪、权力和制作者的角度理解绘画、房间与器物。"), focus:t("Separate the State Apartments, Hall of Mirrors, gardens and Trianon visits if time is limited. Architectural sequences and sight lines are as important as individual objects.","Si le temps est limité, distinguez Grands Appartements, Galerie des Glaces, jardins et Trianon. Enchaînements des salles et perspectives comptent autant que les objets.","时间有限时，可分开参观国王套房、镜厅、花园与特里亚农宫。建筑空间序列和视线关系与单件展品同样重要。"), highlights:t("Hall of Mirrors; State Apartments; gardens and the Trianon estate","Galerie des Glaces ; Grands Appartements ; jardins et domaine de Trianon","镜厅；国王套房；花园与特里亚农庄园") },
];

type RawArtwork = {
  id:string; museumId?:string; artist:string; year:string; imageUrl:string; priority:string;
  title:Record<"en"|"fr"|"zh-Hans",string>; why:Record<"en"|"fr"|"zh-Hans",string>;
  where:Record<"en"|"fr"|"zh-Hans",string>; rarity:Record<"en"|"fr"|"zh-Hans",string>;
  estimate?:{low:number;high:number};
};
const louvreCurated: RawArtwork[] = [{
  id:"cl010062370",museumId:"louvre",artist:"Leonardo da Vinci",year:"c. 1503–1519",priority:"golden20",
  imageUrl:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_natural_color.jpg/960px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_natural_color.jpg",
  title:{en:"Mona Lisa",fr:"La Joconde","zh-Hans":"蒙娜丽莎"},
  why:{en:"Leonardo uses a portrait to test how a living presence can be built from tiny transitions of light, shadow, skin, landscape and gaze.",fr:"Léonard fait du portrait une recherche sur la présence vivante, construite par d’infimes passages entre lumière, ombre, peau, paysage et regard.","zh-Hans":"达·芬奇借肖像探索如何通过光、影、肌肤、风景与目光之间的细微过渡，塑造鲜活的存在感。"},
  where:{en:"Start with the crossed hands, then move to the mouth and away to the eyes. The expression shifts because Leonardo built it from soft shadow rather than hard outlines.",fr:"Commencez par les mains croisées, puis regardez la bouche et enfin les yeux. L’expression change parce que Léonard la construit par des ombres douces plutôt que par des contours nets.","zh-Hans":"先看交叠的双手，再移向嘴角与眼睛。表情之所以变化，是因为达·芬奇以柔和阴影而非硬轮廓塑造它。"},
  rarity:{en:"Autograph paintings by Leonardo are exceptionally few, and this is one of the clearest public encounters with his mature sfumato technique.",fr:"Les peintures autographes de Léonard sont exceptionnellement rares ; celle-ci offre l’une des rencontres publiques les plus directes avec son sfumato parvenu à maturité.","zh-Hans":"达·芬奇亲笔画作极少，这件作品是公众理解其成熟晕涂法最直接的机会之一。"}
}];
const rawArtworks = [...louvreCurated,...(artworksJson as RawArtwork[])];
export const slugify = (value:string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
export const artworks = rawArtworks.map((a) => ({
  ...a,
  museumId: a.museumId || "orsay",
  slug: `${slugify(a.title.en)}-${a.id}`,
  readiness: "SEO_READY_CURATED" as SeoReadiness,
}));

export const museumBySlug = (slug:string) => museums.find((m) => m.slug === slug);
export const artworkBySlug = (slug:string) => artworks.find((a) => a.slug === slug);
export const museumForArtwork = (artwork:typeof artworks[number]) => museums.find((m) => m.id === artwork.museumId)!;
export const localizedArtwork = (a:typeof artworks[number], locale:SeoLocale) => {
  const key = locale === "zh-hans" ? "zh-Hans" : locale;
  return { title:a.title[key], why:a.why[key], where:a.where[key], rarity:a.rarity[key] };
};
export const alternatesFor = (path:string) => ({
  canonical: `${SITE_URL}${path}`,
  languages: { en:`${SITE_URL}/en${path.replace(/^\/(?:en|fr|zh-hans)/,"")}`, fr:`${SITE_URL}/fr${path.replace(/^\/(?:en|fr|zh-hans)/,"")}`, "zh-Hans":`${SITE_URL}/zh-hans${path.replace(/^\/(?:en|fr|zh-hans)/,"")}`, "x-default":`${SITE_URL}/en${path.replace(/^\/(?:en|fr|zh-hans)/,"")}` },
});
