import Link from "next/link";

type PrivacyLocale = "en" | "fr" | "zh-hans";

const copy = {
  en: { title: "Privacy", updated: "Last updated: 4 September 2026", intro: "This page describes the data handling currently implemented by ELYIO.", camera: "Camera and recognition", cameraBody: "When you scan, the selected artwork image is sent to the ELYIO recognition backend for candidate matching and visual verification. Recognition attempts and outcomes are recorded for operational reliability and product analytics. The repository does not establish a blanket deletion period for every attempt, so no fixed deletion promise is made here.", location: "Museum and location", locationBody: "ELYIO may request browser geolocation to suggest a nearby museum. You can deny it and choose a museum manually. The selected museum and visit state may be kept in browser storage for the visit.", analytics: "Analytics and storage", analyticsBody: "Consent-gated first-party events, Google Analytics and PostHog integrations are present in the application. Anonymous/session identifiers, consent state and visit progress may be stored in localStorage or sessionStorage. ELYIO does not cache recognition API responses, camera data or visitor images in its service worker.", providers: "Service providers", providersBody: "The implemented integrations include Supabase, the ELYIO backend hosting environment, OpenAI model endpoints for recognition, Google Analytics and PostHog. Data handling by those providers is governed by their own terms and privacy notices.", choices: "Your choices", choicesBody: "You may deny analytics consent, deny camera or location permissions, choose a museum manually, clear browser storage, or stop using the service. For access, deletion or other privacy requests, owner contact details are still required.", owner: "OWNER_INPUT_REQUIRED: legal entity name, privacy contact email and postal address are not present in the repository and have not been invented.", back: "Back to ELYIO" },
  fr: { title: "Confidentialité", updated: "Dernière mise à jour : 4 septembre 2026", intro: "Cette page décrit le traitement actuellement implémenté par ELYIO.", camera: "Caméra et reconnaissance", cameraBody: "Lors d’un scan, l’image choisie est envoyée au serveur de reconnaissance ELYIO pour la recherche de candidats et la vérification visuelle. Les tentatives et résultats sont enregistrés pour la fiabilité et les analyses produit. Aucun délai général de suppression n’est établi dans le code ; aucune durée fixe n’est donc promise.", location: "Musée et localisation", locationBody: "ELYIO peut demander la géolocalisation du navigateur pour suggérer un musée proche. Vous pouvez la refuser et choisir un musée manuellement. Le musée choisi et l’état de visite peuvent être conservés dans le stockage du navigateur.", analytics: "Analyses et stockage", analyticsBody: "Les événements first-party, Google Analytics et PostHog sont soumis au consentement. Des identifiants anonymes/de session, le consentement et la progression peuvent être conservés dans localStorage ou sessionStorage. Le service worker ne met pas en cache les réponses de reconnaissance, les données caméra ni les images des visiteurs.", providers: "Prestataires", providersBody: "Les intégrations comprennent Supabase, l’hébergement du backend ELYIO, les endpoints OpenAI, Google Analytics et PostHog. Consultez leurs propres conditions et politiques de confidentialité.", choices: "Vos choix", choicesBody: "Vous pouvez refuser les analyses, la caméra ou la localisation, choisir un musée manuellement, effacer le stockage du navigateur ou cesser d’utiliser le service. Les coordonnées du responsable restent à fournir pour les demandes de droits.", owner: "OWNER_INPUT_REQUIRED : entité juridique, e-mail de confidentialité et adresse postale absents du dépôt ; aucune information n’a été inventée.", back: "Retour à ELYIO" },
  "zh-hans": { title: "隐私", updated: "更新日期：2026年9月4日", intro: "本页说明 ELYIO 当前代码中实际实现的数据处理方式。", camera: "相机与识别", cameraBody: "扫描时，所选作品图像会发送到 ELYIO 识别后端，用于候选匹配和视觉核验。识别尝试与结果会为可靠性和产品分析而记录。代码没有规定所有尝试的统一删除期限，因此本页不作固定期限承诺。", location: "博物馆与位置", locationBody: "ELYIO 可能请求浏览器定位，以建议附近博物馆。你可以拒绝并手动选择博物馆。所选博物馆和参观状态可能保存在浏览器存储中。", analytics: "分析与存储", analyticsBody: "应用包含经同意启用的第一方事件、Google Analytics 和 PostHog。匿名/会话标识、同意状态和参观进度可能保存在 localStorage 或 sessionStorage 中。服务 worker 不缓存识别 API 响应、相机数据或访客图像。", providers: "服务提供商", providersBody: "已实现的集成包括 Supabase、ELYIO 后端托管环境、OpenAI 模型接口、Google Analytics 和 PostHog。各服务商的数据处理受其自身条款和隐私政策约束。", choices: "你的选择", choicesBody: "你可以拒绝分析、相机或定位权限，手动选择博物馆，清除浏览器存储，或停止使用服务。若要提出访问或删除请求，仍需补充负责人联系方式。", owner: "OWNER_INPUT_REQUIRED：代码库中没有法律实体名称、隐私邮箱和邮寄地址，页面未自行编造。", back: "返回 ELYIO" },
} as const;

export default function PrivacyContent({ locale }: { locale: PrivacyLocale }) {
  const c = copy[locale];
  return <main className="mx-auto w-full max-w-3xl px-6 py-16 text-[#181714]"><Link href={`/${locale}`} className="text-sm underline">{c.back}</Link><h1 className="mt-10 text-5xl font-semibold">{c.title}</h1><p className="mt-3 text-sm text-neutral-600">{c.updated}</p><p className="mt-8 text-lg">{c.intro}</p>{[[c.camera,c.cameraBody],[c.location,c.locationBody],[c.analytics,c.analyticsBody],[c.providers,c.providersBody],[c.choices,c.choicesBody]].map(([h,b])=><section key={h} className="mt-10"><h2 className="text-2xl font-semibold">{h}</h2><p className="mt-3 leading-7 text-neutral-700">{b}</p></section>)}<p className="mt-10 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm">{c.owner}</p></main>;
}
